### ISSUE TITLE
Investigate where raw data files will be stored (file path)

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-sprout#160]
How are raw data files saved? On Fly.io, it makes sense that they are saved on their servers. But what about for self-hosted installs? Where should they be saved? How does that work and how can users at least see them (but not edit)?

**Comment by philter87** [comment]
In my current (very simple) implementation, the files are stored in the folder called 'persistent_storage'. 

This works well with:
- fly.io, because we can just mount a fly volume
- docker, because we can also just mount a volume
- locally, because it is just stored in the persistent_storage folder

**How to download?**
However, we cannot just serve these assets in the statics folder. We need to have more control. 

Therefore, we also persist some metadata for every file upload. Every file is tied to a table and the table defines who have access to its data.
