### ISSUE TITLE
Discussion: How do we handle informing user of problems in csv file before uploading?

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-sprout#167]
During the validation check, how do we go about telling the user of problems of importing the data? Do we cancel the upload? Do we only inform? Depends on severity?

**Comment by K-Beicher** [comment]
In Redcap you get an intermediate page where it groups your warnings into two, there are those that are not optimal but won't stop you from uploading (eg. they violate best practice, but aren't actually detrimental to the system), and those that are direct violations.  If you only have warnings you get a button at the bottom to say Upload despite warnings, as well as a Discard the upload button.  If there are actual violations you only get the discard button.

What would be nice is a button to say, download all my warnings and errors so that I can work on them offline before the Discard upload is pressed.

**Comment by lwjohnst86** [comment]
I think we decided on downloading all the problems as a csv file, rather than show as a page (makes it easier for us to implement too).
