### ISSUE TITLE
Use frictionless data to extract the schema, rather than Polars

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-sprout#493]
There is a Python package for extracting the metadata, https://v4.framework.frictionlessdata.io/docs/guides/describing-data

So it might look like:

``` python
from frictionless import Schema

schema = Schema.describe("country-1.csv")
schema.to_yaml("country.schema.yaml") 
```

If we follow the frictionless approach, this would make it easier to integrate with them.

**Comment by signekb** [comment]
`frictionless` can definitely be used to extract an initial schema (for csv files*). We just need to find a way to save it to a db instead of a file. 

In #544, I have added `frictionless` with sql to our dependencies. From the [documentation](https://framework.frictionlessdata.io/docs/formats/sql.html), it seems that `frictionless` supports both read and write from sql. 

*Frictionless doesn't support extraction from e.g., `.txt` files with data (at least as far as I understand).

**Comment by lwjohnst86** [comment]
We've already started doing this!
