### ISSUE TITLE
Discussion: Use Common Data Model?

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-sprout#50]
> I'm leaning towards a model where we skip the common data model for now, we can add them in version 15 or so...

_Originally posted by @K-Beicher in https://github.com/seedcase-project/seedcase-sprout/pull/30#discussion_r1439200828_
            
@K-Beicher, could you expand on what you mean here? What model are you thinking about?

**Comment by K-Beicher** [comment]
I believe that I was thinking of the maintenance of a set of table schemas that a researcher can pick from if they are uploading data from a particular machine, or otherwise standard variable names and definitions.  It is something that I'd really like us to offer, but it is also something that will take a lot of time to collate and make available.  Better for now to focus on setting up a system where it will be easy for the person creating the data ressource tables to create their own field names and descriptions.

**Comment by lwjohnst86** [comment]
Some sources to look through and refer to:

- https://en.wikipedia.org/wiki/Observational_Health_Data_Sciences_and_Informatics
- https://www.ohdsi.org/

**Comment by lwjohnst86** [comment]
Not sure this is relevant anymore now. Or maybe it will be later, but with the use of Frictionless data, I think this is less of an issue.
