### ISSUE TITLE
Discussion: Should we only store metadata in the database and not the actual data?

### ISSUE THREAD

**Issue by philter87** [seedcase-project/seedcase-sprout#62]
We might be able to postpone importing the actual data into the database and just store the raw CSV files. The metadata would be stored in the database but it should be database "agnostic" (not dependent on a specific database type)

Reasons not to put the data in the database and only store raw CSV files (or maybe in parquet files)
1. **Implementation complexity**. We do not need to dynamically create Postgres tables based on the data, which would take time. We only need to store the meta data for a table
2. **Portability**. Seedcase is more portable if we do not require a certain database like Postgres. Administrators can use whatever database they like (even SQLite)
3. **Local development**. Seedcase will be easier to test and run locally, when we are not tied to Postgres (we will be less reliant on docker because we can use SQLite)

What do you think? 
@lwjohnst86 @signekb @K-Beicher 
We can also discus this at a update meeting

**Comment by K-Beicher** [comment]
My main concern with this would be how we store the files so that users can't edit them thus rendering the meta data in the database unusable.  There is also an issue with access control, if the data is in a database, then the control is solely in the hands of the admin, if we decide to store them next to the database, then they rely on their IT department to manage access to the files/folders.

Let's have a discussion on this in an update meeting.

**Comment by philter87** [comment]
polars.write_database handles all of my concerts so it is almost as easy to store it in the database as in a parquet file

**Comment by lwjohnst86** [comment]
I think from this discussion that we can easily store thee data in a database via polars, even if we hypothetically don't implement access to it through Sprout. Closing as decided.
