### ISSUE TITLE
Create and test `verify_package_properties()` - a part of `edit_package_properties()`

### ISSUE THREAD

**Issue by signekb** [seedcase-project/seedcase-sprout#712]
Signature: `verify_package_properties(properties: json/dict) -> json/dict:`

- Checks that all fields and values match the spec 
- Checks that required fields are present

Args: 

- `properties`: JSON object of the package following the Data Package spec

Returns: 

- JSON object or Error 

Context: See diagram in the [Core Python functions](https://sprout.seedcase-project.org/docs/design/implementation/python-functions) post.

**Comment by martonvago** [comment]
@lwjohnst86 Which package properties do we want to treat as required in the end?

**Comment by martonvago** [comment]
And what do we want to do with `None` values? If a required field is `None` that should obviously fail validation. But what about other criteria given in the spec? Because a `None` field will fail the type check during `Package.validate_descriptor`. 

Options: 1) ignore these errors coming from frictionless, 2) remove these fields from the `dict`/json object, making it compliant with the spec. 
I think I’d prefer 2, but I’m not sure at which point in the flow we should remove them. My initial feeling is to have the `*Properties` classes spit out a `dict` representation without them, as this would nip the problem in the bud. 
This would mean not having `null` fields written to `datapackage.json` — would we be happy with this? After all, a `datapackage.json` with `null` values is not valid according to the spec.

**Comment by lwjohnst86** [comment]
Hm, if a required field has none, we give an error and inform the user to add it. The only time there are `None`/`null` values in the `datapackage.json` is right after creating the structure with `create_package_structure()`. After that is the `edit_package_properties()`, which is the point in the flow that the user adds the correct fields. For items that are not package properties (e.g. resources that don't exist yet), we could potentially pass the validator only the package fields.

**Comment by martonvago** [comment]
I guess I'm still a bit unclear about optional fields (e.g. `homepage` or `image`). We have all fields set to `None` by default, including optional ones, so when a user passes a `PackageProperties` object with only the required fields set to some value to `edit_package_properties`, then we still have the question of what to do with the unset fields. They are `None` in both the `current_properties` coming from `datapackage.json` and `new_properties` coming from the user, so the result of joining these two can only be `None`. But writing that out to the `datapackage.json` wouldn't give a valid package (even if we ignore the resources). That's why I'm wondering about dropping these unset optional fields. Does my question make sense? 😅 

As for the field `resources`, yeah, I think here we should just ignore that / expect it to be empty.

**Comment by lwjohnst86** [comment]
So even unset optional fields will fail the validator? Hmm, interesting. Can they be set to `""` or something to make it pass?

**Comment by martonvago** [comment]
They fail because they are not the right type (as in, they're `NoneType`, but the spec is expecting e.g. `str`). Yeah, I think changing the default value of each field to a sensible empty value of the correct type would be workable! I'll have a look to see if there are any surprises (e.g. if there are additional format criteria, these will not be satisfied).
