### ISSUE TITLE
Design and finalize data import page for creating a new table

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-sprout#73]

**Comment by henrik-goul** [comment]
The wireframes for data import is ready for a final review, and as agreed during our status talk I will tag you all in here and leave a link to 
@philter87 @signekb @lwjohnst86 @K-Beicher 

Figma:
https://www.figma.com/file/czeKwMxVLKPNQDX42eiTxq/Wireframes?type=design&node-id=0%3A1&mode=design&t=ymjeUcfnmaQ81NNx-1

**Comment by signekb** [comment]
Looks good to me!

**Comment by K-Beicher** [comment]
Happy with these as well, sorry, forgot to go back and add the comment!

**Comment by lwjohnst86** [comment]
Looks great! A comment I have is what @signekb also suggested about having the data extract progress bar being an overlay on the other page, just like the "csv upload" progress bar. Which is the other comment I had, is that is the difference between the progress bars one of uploading and the other of extracting?

**Comment by henrik-goul** [comment]
@signekb @lwjohnst86 
I have adjusted the design so both loading bars are placed in an overlay. The initial consideration I had for the "extracting" loading bar was that if it could take a significant amount of time to extract the data, the design for the loading bar and other feedback we could give the user during the load time could be different. But I believe I have discussed this since then, and that we do not expect the waiting time to be significantly longer than "validating" for example.

If you have no further comments for this (for now at least), I will close the issue :)

**Comment by henrik-goul** [comment]
@lwjohnst86 @signekb @philter87 @K-Beicher wireframes have now been fully reviewed and adjusted, so I have marked them "ready for dev" in Figma (admitttedly a bit late, since you have already come a long way with some implementation ;) ):


![Image](https://github.com/seedcase-project/seedcase-sprout/assets/152619915/306346f6-8683-4d47-82a2-a04c233e3d16)



Task have been moved to done :)
