### ISSUE TITLE
Simplify development and repo by removing all Django stuff

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-sprout#845]
The development feels weird to keep a lot of that stuff even though we don't use it, it no longer reflects the way we do things, and it adds extra files and unnecessary things to the development process (e.g. the GitHub actions).

So maybe it's time to remove all Django content? Especially if we end up not using Django in the end.

**Comment by signekb** [comment]
Uff, this feels a bit ruff, since we spent a lot of time on it. But maybe you're right. Most of it would have to be redone anyways - and we might end up using something else than Django. Even if we'll use Django, it might actually be nicer and cleaner - and maybe quicker as well - just to start from scratch so we feel more in control of what's added.

**Comment by K-Beicher** [comment]
I'm not entirely sure I understand enough about the roll-back function in GitHub, if we remember a piece of code we wrote at some point, how easy would it be to get it back? I think what I'm asking is, should we move it to stand alone repo where we might reference it should we end up going with django later on?

**Comment by signekb** [comment]
It will never be truly gone - the PR will still be there ☺
